Support of development/x major version
scality/bert-e pull request #187
Opened 2024-07-30 22:16 UTC by tcarmet

2024-08-13 15:44 UTC, tcarmet commented on bert_e/workflow/gitwaterflow/queueing.py
> +    name = 'q/w/{}/{}/{}'.format(
breaking change here.

2024-08-14 09:50 UTC, nootal requested changes
Only minor comment.
Quite impressive the amount of code for supporting this new feature.
Great job!

2024-08-14 09:50 UTC, nootal commented on CHANGELOG
> +- Integration queue branches pattern is now `q/w/{pr.id}/{integration.branch}`
Let's make sure we communicate about that; I've looked around through https://github.com/search?q=org%3Ascality+q%2F+language%3Ayaml+path%3A%2F%5E%5C.github%5C%2F%2F&type=code and indeed I don't think it's going to be an issue.

2024-08-14 09:50 UTC, nootal commented on bert_e/lib/versions.py
> +
```suggestion
```

2024-08-14 15:57 UTC, nootal approved these changes

2024-08-14 19:56 UTC, merged